### PR TITLE
nwb_reader_BBP enable having multiple protocol names

### PR DESCRIPTION
**Pull request by anilbey**
This is useful when some nwbs have a slightly different naming of the same
protocol, e.g. IDRest and IDrest (r is lower)

### CODE REVIEW

**Comment by DrTaDa** [comment]
Can you fix the pylint ?

**Comment by anilbey** [comment]
It seems style was the issue @lvsltz .

**Comment by lvsltz** [comment]
I was referring to the behavior of your change, @anilbey.
Is `in_data['protocol_name']` a list now? If so, I think that if `in_data['protocol_name']` is something like `['IDRest', 'IDrest']` and the cell contains the `IDrest` protocol but not `IDRest` (note the case of R), it will not read anything because it will exit with `No eCode IDRest in nwb  path_here`.

In other words, I also had the issue of protocols named differently (also IDthresh/IDthres), and I would like to understand how to use your improvement.

**Comment by anilbey** [comment]
@lvsltz you're right. Tanguy is continuing here https://github.com/BlueBrain/BluePyEfe/pull/42

**Pull request merged**
