### PR TITLE
Fix reader of NWB containing repetitions with leading zeros

### PR DESCRIPTION
**Pull request by lvsltz**
In the temporary new NWB reader, allow parsing of both "repetition n" and "repetition 0n" groups (with leading zeros).

### CODE REVIEW

**Comment by wvangeit** [comment]
There are again some style issues: 
  py3-style run-test: commands[1] | pycodestyle --ignore=E402,W503,W504,E203 bluepyefe
  bluepyefe/reader.py:209:1: W293 blank line contains whitespace
  bluepyefe/reader.py:211:49: E231 missing whitespace after ','
  bluepyefe/reader.py:211:80: W291 trailing whitespace
  bluepyefe/reader.py:212:1: W293 blank line contains whitespace
  bluepyefe/reader.py:215:57: W291 trailing whitespace

**Comment by lvsltz** [comment]
I'll fix them. Is there a link where can I see these issues myself?

**Comment by wvangeit** [comment]
It's best to run the tests yourself before uploading. The command to do that is:
`tox -e py3-unit-functional-style`

**Comment by wvangeit** [comment]
Ok, thanks.
@DrTaDa , you're ok with the change?

**Comment by DrTaDa** [comment]
Yes !

**Pull request merged**
