### PR TITLE
Add a translator for legacy configs

### PR DESCRIPTION
**Pull request by DrTaDa**

### CODE REVIEW

**Review by anilbey — CHANGES_REQUESTED** [review]
Thanks @DrTaDa ! Looks great, can you add test/tests that load the converted files metadata, targets and config using BluePyEfe2 to make sure those converted files will stay valid in the future?

**Comment by anilbey** [comment]
> Thanks @DrTaDa ! Looks great, can you add test/tests that load the converted files metadata, targets and config using BluePyEfe2 to make sure those converted files will stay valid in the future?

E.g. Maybe a small example to show that BPE2 works and extracts the features correctly with those converted configs.

**Comment by DrTaDa** [comment]
@anilbey I fixed too small errors and added at test

**Comment by anilbey** [comment]
Brilliant! There's just some lint issue it seems.

**Review by anilbey — APPROVED** [review]

**Pull request merged**
