### PR TITLE
Keep cron workflow alive

### PR DESCRIPTION
**Pull request by AurelienJaquier**
When the test workflow runs, it checks if the last commit is older than 50 days. If so, it creates a dummy commit to keep the repo active. Attention: this might not get triggered if the tests fail, so we should be vigilant to keep passing tests.

### CODE REVIEW

**Comment by wvangeit** [comment]
You know who will be the author of the commit?

**Comment by wvangeit** [comment]
(and will this only commit in master?)

**Comment by AurelienJaquier** [comment]
Maybe I could separate the workflows, so that the 'keep alive' workflow is only called during scheduled workflows, and not during PRs.

**Comment by anilbey** [comment]
My curiosity, does this workflow also "merge" the new commit to master?

**Comment by AurelienJaquier** [comment]
I believe it does, yes.

**Comment by AurelienJaquier** [comment]
Update: now it should only commit in master

**Comment by wvangeit** [comment]
Ok, let's try it. I'm slightly reluctant to let one of these bots commit into our repo, but we'll see. I wonder how difficult it would be for us to write a shell / python script to do something similar?

**Comment by wvangeit** [comment]
Yes, it seems a 'slight' security risk if the code of the bot gets compromised, but am not too worried. It seems fairly to implement ourselves so that's why I'm suggesting it, but if it's complicated we can keep on using the bot.

**Pull request merged**
